# Generated by Django 4.0.5 on 2022-06-05 14:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profilephoto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profilephoto')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('caption', models.CharField(max_length=80)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.profile')),
            ],
        ),
    ]
